### ISSUE TITLE
Infrastructure v1

### ISSUE THREAD

**Issue by alexpbrown** [ShenaniganDApp/shenanigan-monorepo#175]
We need to lay the groundwork for scalable infrastructure going forward
- Dockerfile that packages up the app
- Nginx proxying web requests and websockets
- local / remote mongodb (spike here to assess options)
- DNS and server certificates -  @youngkidwarrior do we have a name registered?

Nice to have:
- github actions to deploy after tests pass
- docker services or docker-compose.yml to bring things up and down / scale

**Comment by youngkidwarrior** [comment]
Love to see this issue @alexpbrown

We do have a DNS name registered

http://she.energy

**Comment by alexpbrown** [comment]
Yep, I've been using that one as a base to start from! I spent some time digging into yarn / npm dependency issues while building from a fresh checkout - the main problem was with `packages/builder/package.json:28` `"@opengsn/gsn": "git+https://github.com/opengsn/gsn#solc-0.7.5"`, this branch no longer exists. I'll submit some PRs tomorrow.

BTW I'm also trying to spin things up with local mongo (for testing), but it looks like using the remote cluster is hardcoded.

**Comment by youngkidwarrior** [comment]
@alexpbrown yeah we have a PR to fix that. Just remove it, we don't use it anymore!
