### ISSUE TITLE
Create Script for Intro Video

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/shenanigan-monorepo#209]
https://docs.google.com/document/d/1vJq2DJHWNB73uE9GmwcKPJIiOrEzEVI8P1IdmUJP7L0/edit

- Finalize the "story board" of the script

- Very rough example:

First scene: This happens
2nd Scene: Then this happens and voice over says this and this graphic plays
3rd Scene: Quick cut of nip
4th Scene: Explain this aspect and this graphic plays
...

9th Scen: Fin

CELTX SCRIPT LINK:

https://www.celtx.com/a/ux/index#documents/2222564be7c226f904cf4dc47ca57c32c31948di

**Comment by youngkidwarrior** [comment]
@chair28980 wrong repo. Move this to community
