### ISSUE TITLE
SourceCred <--> LP $PRTCLE Minting Redistribution Snapshot Proposal

### ISSUE THREAD

**Issue by duckcmdr** [ShenaniganDApp/shenanigan-monorepo#230]
Write a Snapshot proposal that addresses the option of halving the 20,000 minted SourceCred PRTCLE, redistributing half of it to a weighted LP rewards pool.

**PROS**
- Incentivizes liquidity providers
- Would increase SHE liquidity and raise token ranking in Honeyswap
- Would allow for concrete APY for staking
- Rewards those who purchase $PRTCLE directly on the marketplace with intent to stake

**CONS**
- Would cut into incentive for Discord CRED participation
- Could possibly alienate community members who don't hold large bags

**Comment by youngkidwarrior** [comment]
hey @duckcmdr this doesn't belong in shenanigan-monorepo repository. This is probably better for operations
