### ISSUE TITLE
Send backdated PRTCLE to SourceCred and DAO

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/shenanigan-monorepo#242]
The 4/26 - 5/17 distributions were distributed, but the SourceCred balance and DAO balance needs to be paid.

Find the amounts from the ledger, and send.

**Comment by youngkidwarrior** [comment]
move this to scoreboard repo

**Comment by chair28980** [comment]
CLOSED in favor of this ticket in the correct repo: https://app.zenhub.com/workspaces/shenanigan-605a78c794095d001a527c29/issues/shenanigandapp/scoreboard/28
