### ISSUE TITLE
Animate BottomSheet Blurview

### ISSUE THREAD

**Issue by stormcloud266** [ShenaniganDApp/shenanigan-monorepo#243]
When the BottomSheet component opens, the BlurView background overlay snaps in. This should be animated to fade in/out.

Could be added as [backdrop component](https://gorhom.github.io/react-native-bottom-sheet/props#backdropcomponent).

**Comment by chair28980** [comment]
Related to https://app.zenhub.com/workspaces/shenanigan-605a78c794095d001a527c29/issues/shenanigandapp/shenanigan-monorepo/170
